global using Domain.Models;
global using Microsoft.EntityFrameworkCore;
global using Application.DTO;
global using Application.Exceptions;
global using Application.Extensions;
global using Domain.ValueObjects;
global using Microsoft.Extensions.Logging;
global using Application.Data.DataBaseContext;
global using Shared.CQRS;